import type { Trip, Day } from '../types/trip';

const STORAGE_KEY = 'tripplan_trips';

const sampleTrips: Trip[] = [
  {
    id: 1,
    title: '京都・奈良の週末',
    destination: '京都・奈良',
    startDate: '2025-10-18',
    endDate: '2025-10-20',
    cover: '🏯',
    days: [
      {
        date: '2025-10-18',
        spots: [
          {
            id: 1,
            name: '清水寺',
            startTime: '09:00',
            duration: 90,
            category: '観光',
            note: '舞台からの眺めが最高。早めに行く。',
            url: 'https://www.kiyomizudera.or.jp/',
            costs: [{ label: '拝観料', amount: '400' }],
          },
          {
            id: 2,
            name: '祇園散策',
            startTime: '11:00',
            duration: 60,
            category: '散策',
            note: '雰囲気のある路地を歩く',
            url: 'https://www.gion.or.jp/',
            costs: [{ label: 'おやつ', amount: '800' }],
          },
        ],
      },
      {
        date: '2025-10-19',
        spots: [
          {
            id: 3,
            name: '東大寺',
            startTime: '10:00',
            duration: 120,
            category: '観光',
            note: '大仏殿と二月堂を見学',
            url: 'https://www.todaiji.or.jp/',
            costs: [{ label: '拝観料', amount: '500' }],
          },
          {
            id: 4,
            name: '奈良公園で鹿せんべい',
            startTime: '12:30',
            duration: 45,
            category: '体験',
            note: 'のんびり散策',
            url: 'https://www.pref.nara.jp/park/index.html',
            costs: [{ label: 'せんべい', amount: '200' }],
          },
        ],
      },
      {
        date: '2025-10-20',
        spots: [
          {
            id: 5,
            name: '嵐山竹林',
            startTime: '09:30',
            duration: 60,
            category: '散策',
            note: '朝の静けさを楽しむ',
            url: 'https://www.japan-guide.com/e/e3912.html',
            costs: [],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: '東京グルメ旅',
    destination: '東京',
    startDate: '2025-12-05',
    endDate: '2025-12-06',
    cover: '🍜',
    days: [
      {
        date: '2025-12-05',
        spots: [
          {
            id: 6,
            name: '築地場外市場',
            startTime: '08:30',
            duration: 90,
            category: 'グルメ',
            note: '朝ごはんに寿司を食べる',
            url: 'https://www.tsukiji.or.jp/',
            costs: [{ label: '朝食', amount: '2500' }],
          },
          {
            id: 7,
            name: '浅草寺',
            startTime: '11:00',
            duration: 60,
            category: '観光',
            note: '仲見世の散策',
            url: 'https://www.senso-ji.jp/',
            costs: [{ label: 'おみくじ', amount: '100' }],
          },
        ],
      },
      {
        date: '2025-12-06',
        spots: [
          {
            id: 8,
            name: '渋谷スクランブル交差点',
            startTime: '10:00',
            duration: 30,
            category: '散策',
            note: '人混みを体験',
            url: 'https://www.shibuya109.jp/',
            costs: [],
          },
          {
            id: 9,
            name: '原宿カフェ',
            startTime: '11:00',
            duration: 90,
            category: 'グルメ',
            note: '話題のパンケーキを食べる',
            url: 'https://www.haruhari.jp/',
            costs: [{ label: 'ランチ', amount: '1800' }],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: '沖縄マリンリゾート',
    destination: '沖縄',
    startDate: '2026-08-01',
    endDate: '2026-08-04',
    cover: '🌺',
    days: [
      {
        date: '2026-08-01',
        spots: [
          {
            id: 10,
            name: '国際通り散策',
            startTime: '15:00',
            duration: 90,
            category: '散策',
            note: '沖縄土産の宝庫。ちんすこうと泡盛を購入',
            url: 'https://www.kokusaidori.net/',
            costs: [{ label: 'お土産', amount: '3000' }],
          },
          {
            id: 11,
            name: '牧志公設市場',
            startTime: '17:00',
            duration: 60,
            category: 'グルメ',
            note: '2階で海鮮を持ち込んで調理してもらえる',
            url: 'https://kosetsu-ichiba.com/',
            costs: [{ label: '夕食', amount: '4000' }],
          },
        ],
      },
      {
        date: '2026-08-02',
        spots: [
          {
            id: 12,
            name: '美ら海水族館',
            startTime: '09:30',
            duration: 150,
            category: '観光',
            note: '世界最大級の水槽でジンベエザメを鑑賞',
            url: 'https://churaumi.okinawa/',
            costs: [{ label: '入場料', amount: '2180' }],
          },
          {
            id: 13,
            name: '古宇利大橋ドライブ',
            startTime: '13:30',
            duration: 90,
            category: '散策',
            note: '沖縄屈指の絶景橋。ハートロック必訪',
            url: 'https://www.nakijin-kankou.jp/',
            costs: [],
          },
          {
            id: 14,
            name: 'ゴーヤチャンプルー夕食',
            startTime: '18:00',
            duration: 60,
            category: 'グルメ',
            note: '地元の定食屋でゴーヤチャンプルーと沖縄そば',
            url: '',
            costs: [{ label: '夕食', amount: '1500' }],
          },
        ],
      },
      {
        date: '2026-08-03',
        spots: [
          {
            id: 15,
            name: '体験ダイビング（慶良間諸島）',
            startTime: '09:00',
            duration: 180,
            category: '体験',
            note: '透明度30m以上の海でダイビング体験。熱帯魚と珊瑚礁',
            url: '',
            costs: [{ label: 'ダイビング料金', amount: '12000' }],
          },
          {
            id: 16,
            name: '残波岬',
            startTime: '14:30',
            duration: 60,
            category: '散策',
            note: '沖縄本島最西端。白い灯台と断崖絶壁が絶景',
            url: '',
            costs: [],
          },
          {
            id: 17,
            name: '琉球料理ディナー',
            startTime: '19:00',
            duration: 90,
            category: 'グルメ',
            note: '泡盛と一緒に琉球の伝統料理を堪能',
            url: '',
            costs: [{ label: 'ディナー', amount: '5000' }],
          },
        ],
      },
      {
        date: '2026-08-04',
        spots: [
          {
            id: 18,
            name: '首里城',
            startTime: '09:00',
            duration: 120,
            category: '観光',
            note: '復元中だが正殿が再建。琉球王国の象徴',
            url: 'https://oki-park.jp/shurijo/',
            costs: [{ label: '観覧料', amount: '400' }],
          },
          {
            id: 19,
            name: '那覇空港お土産',
            startTime: '13:00',
            duration: 60,
            category: '散策',
            note: '免税店で最後の買い物。沖縄限定のお菓子を購入',
            url: '',
            costs: [{ label: '空港土産', amount: '2000' }],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: '北海道冬の旅',
    destination: '北海道',
    startDate: '2026-02-14',
    endDate: '2026-02-17',
    cover: '❄️',
    days: [
      {
        date: '2026-02-14',
        spots: [
          {
            id: 20,
            name: '小樽運河散策',
            startTime: '13:30',
            duration: 120,
            category: '散策',
            note: '運河沿いの石造り倉庫群。ガス灯が美しい夕暮れ時',
            url: 'https://otaru.gr.jp/',
            costs: [],
          },
          {
            id: 21,
            name: '小樽寿司屋通り',
            startTime: '17:00',
            duration: 90,
            category: 'グルメ',
            note: '北海道有数の寿司の街。旬のネタを堪能',
            url: '',
            costs: [{ label: '夕食（寿司）', amount: '6000' }],
          },
        ],
      },
      {
        date: '2026-02-15',
        spots: [
          {
            id: 22,
            name: 'さっぽろ雪まつり',
            startTime: '10:00',
            duration: 180,
            category: '観光',
            note: '大通公園の大雪像を見学。防寒対策必須',
            url: 'https://www.snowfes.com/',
            costs: [],
          },
          {
            id: 23,
            name: 'ジンギスカン夕食',
            startTime: '17:30',
            duration: 90,
            category: 'グルメ',
            note: '北海道の代名詞ジンギスカン。サッポロビール園で',
            url: 'https://www.sapporo-bier-garten.jp/',
            costs: [{ label: '夕食', amount: '3500' }],
          },
        ],
      },
      {
        date: '2026-02-16',
        spots: [
          {
            id: 24,
            name: 'ニセコスキーリゾート',
            startTime: '08:30',
            duration: 360,
            category: '体験',
            note: 'パウダースノーで有名な世界屈指のスキーリゾート',
            url: 'https://www.niseko.ne.jp/',
            costs: [{ label: 'リフト券', amount: '6600' }, { label: 'レンタル用品', amount: '5000' }],
          },
          {
            id: 25,
            name: 'ニセコ温泉',
            startTime: '17:00',
            duration: 90,
            category: '体験',
            note: 'スキー後の露天風呂は格別。羊蹄山を望む絶景',
            url: '',
            costs: [{ label: '入浴料', amount: '800' }],
          },
        ],
      },
      {
        date: '2026-02-17',
        spots: [
          {
            id: 26,
            name: '函館朝市',
            startTime: '07:00',
            duration: 90,
            category: 'グルメ',
            note: 'イカの踊り食いや海鮮丼が名物',
            url: 'https://www.hakodate-asaichi.com/',
            costs: [{ label: '朝食', amount: '2500' }],
          },
          {
            id: 27,
            name: '五稜郭',
            startTime: '10:00',
            duration: 90,
            category: '観光',
            note: '幕末の星型城郭。タワーからの眺めが絶景',
            url: 'https://www.goryokaku-tower.co.jp/',
            costs: [{ label: '入場料', amount: '500' }],
          },
        ],
      },
    ],
  },
  {
    id: 5,
    title: '大阪食い倒れ旅',
    destination: '大阪',
    startDate: '2026-09-12',
    endDate: '2026-09-14',
    cover: '🍡',
    days: [
      {
        date: '2026-09-12',
        spots: [
          {
            id: 28,
            name: '道頓堀',
            startTime: '12:00',
            duration: 90,
            category: 'グルメ',
            note: 'たこ焼きとくいだおれ太郎を見学',
            url: 'https://www.dotonbori.or.jp/',
            costs: [{ label: 'たこ焼き', amount: '600' }],
          },
          {
            id: 29,
            name: '黒門市場',
            startTime: '14:30',
            duration: 60,
            category: 'グルメ',
            note: '天下の台所。試食しながら食材をチェック',
            url: 'https://www.kuromon.com/',
            costs: [{ label: '食べ歩き', amount: '1500' }],
          },
          {
            id: 30,
            name: '通天閣',
            startTime: '16:30',
            duration: 60,
            category: '観光',
            note: '新世界エリアのシンボル。ビリケン像に触れる',
            url: 'https://www.tsutenkaku.co.jp/',
            costs: [{ label: '入場料', amount: '700' }],
          },
          {
            id: 31,
            name: '串カツ夕食',
            startTime: '18:30',
            duration: 90,
            category: 'グルメ',
            note: '二度漬け禁止の本場串カツ',
            url: '',
            costs: [{ label: '夕食', amount: '2000' }],
          },
        ],
      },
      {
        date: '2026-09-13',
        spots: [
          {
            id: 32,
            name: '大阪城',
            startTime: '09:00',
            duration: 120,
            category: '観光',
            note: '天守閣に登り大阪の街を一望',
            url: 'https://www.osakacastle.net/',
            costs: [{ label: '入館料', amount: '600' }],
          },
          {
            id: 33,
            name: 'お好み焼き体験',
            startTime: '12:00',
            duration: 90,
            category: '体験',
            note: '大阪流のお好み焼きを自分で作って食べる',
            url: '',
            costs: [{ label: '材料費', amount: '1500' }],
          },
          {
            id: 34,
            name: '心斎橋ショッピング',
            startTime: '15:00',
            duration: 120,
            category: '散策',
            note: 'アーケード商店街と周辺のおしゃれな店を散策',
            url: '',
            costs: [{ label: 'ショッピング', amount: '5000' }],
          },
        ],
      },
      {
        date: '2026-09-14',
        spots: [
          {
            id: 35,
            name: '住吉大社',
            startTime: '09:00',
            duration: 60,
            category: '観光',
            note: '全国に約2,300社ある住吉神社の総本社',
            url: 'https://www.sumiyoshitaisha.net/',
            costs: [],
          },
          {
            id: 36,
            name: 'ルクア大阪',
            startTime: '11:00',
            duration: 90,
            category: '散策',
            note: 'JR大阪駅直結。帰りの買い物に最適',
            url: '',
            costs: [{ label: 'ショッピング', amount: '3000' }],
          },
          {
            id: 37,
            name: '551蓬莱の豚まん',
            startTime: '13:30',
            duration: 30,
            category: 'グルメ',
            note: '大阪みやげの定番。新大阪駅で購入',
            url: 'https://www.551horai.co.jp/',
            costs: [{ label: '豚まん', amount: '840' }],
          },
        ],
      },
    ],
  },
  {
    id: 6,
    title: '金沢・能登の旅',
    destination: '石川県',
    startDate: '2026-11-07',
    endDate: '2026-11-09',
    cover: '🦀',
    days: [
      {
        date: '2026-11-07',
        spots: [
          {
            id: 38,
            name: '近江町市場',
            startTime: '11:30',
            duration: 90,
            category: 'グルメ',
            note: '金沢の台所。海鮮丼とのどぐろをチェック',
            url: 'https://ohmicho-ichiba.com/',
            costs: [{ label: '昼食（海鮮丼）', amount: '2500' }],
          },
          {
            id: 39,
            name: '兼六園',
            startTime: '14:00',
            duration: 90,
            category: '観光',
            note: '日本三名園のひとつ。秋の紅葉が美しい',
            url: 'https://www.pref.ishikawa.jp/siro-niwa/kenrokuen/',
            costs: [{ label: '入場料', amount: '320' }],
          },
          {
            id: 40,
            name: 'ひがし茶屋街',
            startTime: '16:30',
            duration: 60,
            category: '散策',
            note: '江戸時代の茶屋が立ち並ぶ格調ある街並み',
            url: '',
            costs: [{ label: '抹茶スイーツ', amount: '700' }],
          },
        ],
      },
      {
        date: '2026-11-08',
        spots: [
          {
            id: 41,
            name: '白米千枚田',
            startTime: '10:00',
            duration: 90,
            category: '観光',
            note: '能登の棚田が海沿いに広がる絶景。日本の原風景',
            url: 'https://senmaida.wajima-kankou.jp/',
            costs: [],
          },
          {
            id: 42,
            name: '輪島朝市',
            startTime: '08:00',
            duration: 60,
            category: 'グルメ',
            note: '日本三大朝市のひとつ。新鮮な海産物と地元野菜',
            url: 'https://wajima-asaichi.com/',
            costs: [{ label: '食べ歩き', amount: '1000' }],
          },
          {
            id: 43,
            name: 'のどぐろ夕食',
            startTime: '18:00',
            duration: 90,
            category: 'グルメ',
            note: '金沢が誇るブランド魚のどぐろを塩焼きで',
            url: '',
            costs: [{ label: '夕食', amount: '8000' }],
          },
        ],
      },
      {
        date: '2026-11-09',
        spots: [
          {
            id: 44,
            name: '金沢21世紀美術館',
            startTime: '10:00',
            duration: 120,
            category: '観光',
            note: '円形の現代美術館。スイミングプール作品が人気',
            url: 'https://www.kanazawa21.jp/',
            costs: [{ label: '展覧会チケット', amount: '1200' }],
          },
          {
            id: 45,
            name: '長町武家屋敷跡',
            startTime: '13:00',
            duration: 60,
            category: '散策',
            note: '江戸情緒が漂う土塀と石畳の路地',
            url: '',
            costs: [],
          },
          {
            id: 46,
            name: '金沢おでん',
            startTime: '15:30',
            duration: 60,
            category: 'グルメ',
            note: '全国的にも珍しいおでんの聖地',
            url: '',
            costs: [{ label: 'おでん', amount: '2000' }],
          },
        ],
      },
    ],
  },
  {
    id: 7,
    title: '広島・宮島 平和の旅',
    destination: '広島・宮島',
    startDate: '2026-05-03',
    endDate: '2026-05-04',
    cover: '🕊️',
    days: [
      {
        date: '2026-05-03',
        spots: [
          {
            id: 47,
            name: '広島平和記念公園',
            startTime: '09:00',
            duration: 60,
            category: '観光',
            note: '原爆ドームと平和の灯。心静かに訪問',
            url: 'https://www.pcf.city.hiroshima.jp/',
            costs: [],
          },
          {
            id: 48,
            name: '広島平和記念資料館',
            startTime: '10:30',
            duration: 90,
            category: '観光',
            note: '原爆の記録と被爆者の声。事前予約推奨',
            url: 'https://hpmmuseum.jp/',
            costs: [{ label: '入場料', amount: '200' }],
          },
          {
            id: 49,
            name: '広島流お好み焼き',
            startTime: '13:00',
            duration: 60,
            category: 'グルメ',
            note: '広島流お好み焼きは麺入り。地元の名店で',
            url: '',
            costs: [{ label: '昼食', amount: '1200' }],
          },
          {
            id: 50,
            name: '厳島神社',
            startTime: '15:30',
            duration: 90,
            category: '観光',
            note: '世界遺産の海に浮かぶ神社。潮の満ち引きで景色が変わる',
            url: 'https://www.itsukushimajinja.jp/',
            costs: [{ label: '参拝料', amount: '300' }],
          },
        ],
      },
      {
        date: '2026-05-04',
        spots: [
          {
            id: 51,
            name: '弥山登山',
            startTime: '08:00',
            duration: 180,
            category: '体験',
            note: 'ロープウェイと徒歩で山頂へ。瀬戸内海の絶景',
            url: '',
            costs: [{ label: 'ロープウェイ代', amount: '2000' }],
          },
          {
            id: 52,
            name: '宮島もみじ饅頭食べ比べ',
            startTime: '12:00',
            duration: 60,
            category: 'グルメ',
            note: '揚げもみじ饅頭も美味。生もみじも試す',
            url: '',
            costs: [{ label: 'もみじ饅頭', amount: '1500' }],
          },
          {
            id: 53,
            name: '帰路（しゃもじかきめし）',
            startTime: '15:00',
            duration: 30,
            category: '散策',
            note: '広島駅で駅弁の「しゃもじかきめし」を購入して帰路',
            url: '',
            costs: [{ label: '駅弁', amount: '1400' }],
          },
        ],
      },
    ],
  },
  {
    id: 8,
    title: '箱根温泉と富士山',
    destination: '箱根・富士山',
    startDate: '2026-04-04',
    endDate: '2026-04-06',
    cover: '🗻',
    days: [
      {
        date: '2026-04-04',
        spots: [
          {
            id: 54,
            name: '箱根湯本散策',
            startTime: '11:00',
            duration: 60,
            category: '散策',
            note: '温泉まんじゅうを食べながら早川沿いを散策',
            url: '',
            costs: [{ label: '温泉まんじゅう', amount: '500' }],
          },
          {
            id: 55,
            name: '箱根関所跡',
            startTime: '13:00',
            duration: 90,
            category: '観光',
            note: '江戸時代の東海道随一の関所。芦ノ湖畔に位置',
            url: 'https://www.hakonesekisyo.jp/',
            costs: [{ label: '入館料', amount: '500' }],
          },
          {
            id: 56,
            name: '芦ノ湖遊覧船',
            startTime: '15:00',
            duration: 60,
            category: '体験',
            note: '湖上から富士山を眺める。晴れていれば最高',
            url: '',
            costs: [{ label: '遊覧船代', amount: '1200' }],
          },
          {
            id: 57,
            name: '温泉旅館',
            startTime: '17:30',
            duration: 120,
            category: '宿泊',
            note: '露天風呂付き旅館。夕食は懐石料理',
            url: '',
            costs: [{ label: '宿泊費', amount: '25000' }],
          },
        ],
      },
      {
        date: '2026-04-05',
        spots: [
          {
            id: 58,
            name: '富士山五合目',
            startTime: '09:00',
            duration: 120,
            category: '観光',
            note: '富士スバルラインで五合目へ。雪が残る時期',
            url: 'https://www.fujisan-climb.jp/',
            costs: [{ label: 'バス代', amount: '2100' }],
          },
          {
            id: 59,
            name: '朝霧高原',
            startTime: '13:30',
            duration: 90,
            category: '散策',
            note: '牧場と富士山の絶景コンビ。ソフトクリームが美味',
            url: '',
            costs: [{ label: 'ソフトクリーム', amount: '400' }],
          },
        ],
      },
      {
        date: '2026-04-06',
        spots: [
          {
            id: 60,
            name: '大涌谷',
            startTime: '09:30',
            duration: 60,
            category: '観光',
            note: '活火山の噴煙地帯。黒たまご1個で7年長生き',
            url: 'https://www.owakudani.com/',
            costs: [{ label: '黒たまご', amount: '600' }],
          },
          {
            id: 61,
            name: '箱根ガラスの森美術館',
            startTime: '11:30',
            duration: 90,
            category: '観光',
            note: 'ヴェネチアンガラス作品と庭園。入口のクリスタルツリーが見事',
            url: 'https://www.hakone-garasunomori.jp/',
            costs: [{ label: '入場料', amount: '1800' }],
          },
          {
            id: 62,
            name: '小田原城',
            startTime: '14:30',
            duration: 90,
            category: '観光',
            note: '関東地方の名城。桜の名所でもある',
            url: 'https://www.city.odawara.kanagawa.jp/odawara-castle/',
            costs: [{ label: '入場料', amount: '510' }],
          },
        ],
      },
    ],
  },
  {
    id: 9,
    title: '長崎・歴史と異国情緒',
    destination: '長崎',
    startDate: '2026-03-07',
    endDate: '2026-03-09',
    cover: '🌐',
    days: [
      {
        date: '2026-03-07',
        spots: [
          {
            id: 63,
            name: 'グラバー園',
            startTime: '12:00',
            duration: 90,
            category: '観光',
            note: '明治期の外国人居留地。日本最古の洋風住宅',
            url: 'https://www.glover-garden.jp/',
            costs: [{ label: '入場料', amount: '620' }],
          },
          {
            id: 64,
            name: '大浦天主堂',
            startTime: '14:30',
            duration: 45,
            category: '観光',
            note: '国宝に指定された日本最古のゴシック建築の教会',
            url: 'https://www.oura-church.jp/',
            costs: [{ label: '入場料', amount: '1000' }],
          },
          {
            id: 65,
            name: 'オランダ坂散策',
            startTime: '16:00',
            duration: 60,
            category: '散策',
            note: '石畳の坂道と洋風建築が並ぶ異国情緒あふれる街',
            url: '',
            costs: [],
          },
          {
            id: 66,
            name: '長崎ちゃんぽん夕食',
            startTime: '18:00',
            duration: 60,
            category: 'グルメ',
            note: '発祥の地で本場のちゃんぽんを。四海楼が元祖',
            url: 'https://www.shikairoh.com/',
            costs: [{ label: '夕食', amount: '1200' }],
          },
        ],
      },
      {
        date: '2026-03-08',
        spots: [
          {
            id: 67,
            name: '長崎原爆資料館',
            startTime: '09:00',
            duration: 90,
            category: '観光',
            note: '長崎の被爆の記録。平和公園と合わせて訪問',
            url: 'https://nagasakipeace.jp/',
            costs: [{ label: '入館料', amount: '200' }],
          },
          {
            id: 68,
            name: '平和公園',
            startTime: '10:30',
            duration: 60,
            category: '散策',
            note: '平和の像と祈りの場',
            url: '',
            costs: [],
          },
          {
            id: 69,
            name: '稲佐山展望台',
            startTime: '20:00',
            duration: 60,
            category: '観光',
            note: '日本三大夜景のひとつ。ロープウェイで山頂へ',
            url: 'https://www.nagasaki-ropeway.jp/',
            costs: [{ label: 'ロープウェイ', amount: '1250' }],
          },
        ],
      },
      {
        date: '2026-03-09',
        spots: [
          {
            id: 70,
            name: '出島',
            startTime: '09:00',
            duration: 90,
            category: '観光',
            note: '江戸時代の唯一の西洋窓口。復元された出島ワーフ',
            url: 'https://nagasakidejima.jp/',
            costs: [{ label: '入場料', amount: '510' }],
          },
          {
            id: 71,
            name: '眼鏡橋',
            startTime: '11:00',
            duration: 30,
            category: '散策',
            note: '日本最古の石造りアーチ橋。川面に映る姿が眼鏡のよう',
            url: '',
            costs: [],
          },
          {
            id: 72,
            name: 'カステラ購入',
            startTime: '12:30',
            duration: 30,
            category: 'グルメ',
            note: '福砂屋や文明堂の老舗でカステラをお土産に',
            url: '',
            costs: [{ label: 'カステラ', amount: '2000' }],
          },
        ],
      },
    ],
  },
  {
    id: 10,
    title: '屋久島縄文杉トレッキング',
    destination: '屋久島',
    startDate: '2026-09-19',
    endDate: '2026-09-22',
    cover: '🌲',
    days: [
      {
        date: '2026-09-19',
        spots: [
          {
            id: 73,
            name: '千尋の滝',
            startTime: '14:30',
            duration: 60,
            category: '観光',
            note: '巨大な花崗岩一枚岩を流れ落ちる滝',
            url: '',
            costs: [],
          },
          {
            id: 74,
            name: '屋久島の夕食',
            startTime: '18:00',
            duration: 60,
            category: 'グルメ',
            note: '首折れサバなど屋久島の新鮮な海の幸を堪能',
            url: '',
            costs: [{ label: '夕食', amount: '3500' }],
          },
        ],
      },
      {
        date: '2026-09-20',
        spots: [
          {
            id: 75,
            name: '縄文杉トレッキング（往路）',
            startTime: '05:00',
            duration: 300,
            category: '体験',
            note: '22kmの往復。早起き必須。ガイドツアー参加推奨',
            url: '',
            costs: [{ label: 'ガイド料', amount: '8000' }],
          },
          {
            id: 76,
            name: '縄文杉',
            startTime: '10:00',
            duration: 30,
            category: '観光',
            note: '樹齢7200年以上ともいわれる巨大杉。感動的な圧倒感',
            url: '',
            costs: [],
          },
          {
            id: 77,
            name: 'トレッキング復路',
            startTime: '10:30',
            duration: 240,
            category: '体験',
            note: '帰りの道のり。足腰への負担大、ストック推奨',
            url: '',
            costs: [],
          },
        ],
      },
      {
        date: '2026-09-21',
        spots: [
          {
            id: 78,
            name: '白谷雲水峡',
            startTime: '08:00',
            duration: 180,
            category: '体験',
            note: '苔むす森はもののけ姫のモデル地。水の音が心地よい',
            url: '',
            costs: [{ label: '入山料', amount: '300' }],
          },
          {
            id: 79,
            name: '平内海中温泉',
            startTime: '17:00',
            duration: 60,
            category: '体験',
            note: '干潮時のみ入れる海辺の野天風呂。無料だが時間注意',
            url: '',
            costs: [],
          },
        ],
      },
      {
        date: '2026-09-22',
        spots: [
          {
            id: 80,
            name: '西部林道',
            startTime: '07:00',
            duration: 90,
            category: '散策',
            note: '世界遺産の原生林。ヤクザルとヤクシカに出会える',
            url: '',
            costs: [],
          },
          {
            id: 81,
            name: '屋久島空港お土産',
            startTime: '13:00',
            duration: 60,
            category: '散策',
            note: '屋久杉クラフトと三岳（焼酎）を購入',
            url: '',
            costs: [{ label: 'お土産', amount: '5000' }],
          },
        ],
      },
    ],
  },
  {
    id: 11,
    title: '仙台・松島・平泉',
    destination: '宮城・岩手',
    startDate: '2026-05-16',
    endDate: '2026-05-18',
    cover: '🌸',
    days: [
      {
        date: '2026-05-16',
        spots: [
          {
            id: 82,
            name: '松島海岸',
            startTime: '10:00',
            duration: 90,
            category: '観光',
            note: '日本三景のひとつ。島々が点在する美しい海岸線',
            url: 'https://www.matsushima-kanko.com/',
            costs: [],
          },
          {
            id: 83,
            name: '瑞巌寺',
            startTime: '12:00',
            duration: 60,
            category: '観光',
            note: '政宗公が造営した東北屈指の禅寺',
            url: 'https://www.zuiganji.or.jp/',
            costs: [{ label: '拝観料', amount: '700' }],
          },
          {
            id: 84,
            name: '松島の牡蠣焼き',
            startTime: '13:30',
            duration: 60,
            category: 'グルメ',
            note: '松島は牡蠣の名産地。浜焼きが美味',
            url: '',
            costs: [{ label: '牡蠣焼き', amount: '2000' }],
          },
        ],
      },
      {
        date: '2026-05-17',
        spots: [
          {
            id: 85,
            name: '平泉・中尊寺',
            startTime: '09:00',
            duration: 120,
            category: '観光',
            note: '世界遺産。金色堂は圧巻の荘厳さ',
            url: 'https://www.chusonji.or.jp/',
            costs: [{ label: '拝観料', amount: '800' }],
          },
          {
            id: 86,
            name: '毛越寺',
            startTime: '12:00',
            duration: 60,
            category: '観光',
            note: '平安時代の浄土庭園。蓮の花が美しい季節に',
            url: 'https://www.motsuji.or.jp/',
            costs: [{ label: '拝観料', amount: '500' }],
          },
          {
            id: 87,
            name: '仙台牛タン',
            startTime: '18:00',
            duration: 90,
            category: 'グルメ',
            note: '仙台名物の牛タン定食。麦飯とテールスープが付く',
            url: '',
            costs: [{ label: '夕食', amount: '2500' }],
          },
        ],
      },
      {
        date: '2026-05-18',
        spots: [
          {
            id: 88,
            name: '仙台城跡（青葉城）',
            startTime: '09:30',
            duration: 60,
            category: '観光',
            note: '伊達政宗公の銅像と仙台の眺望',
            url: 'https://www.sendaijo.com/',
            costs: [],
          },
          {
            id: 89,
            name: 'ずんだシェイク',
            startTime: '12:00',
            duration: 30,
            category: 'グルメ',
            note: '仙台駅のずんだ茶寮で締め。お土産にずんだ餅も',
            url: 'https://www.zundamochi.com/',
            costs: [{ label: 'ずんだシェイク', amount: '450' }],
          },
        ],
      },
    ],
  },
  {
    id: 12,
    title: '鎌倉・江ノ島',
    destination: '神奈川',
    startDate: '2026-10-03',
    endDate: '2026-10-04',
    cover: '⛩️',
    days: [
      {
        date: '2026-10-03',
        spots: [
          {
            id: 90,
            name: '北鎌倉・円覚寺',
            startTime: '09:00',
            duration: 60,
            category: '観光',
            note: '臨済宗円覚寺派の大本山。鎌倉五山第二位',
            url: 'https://www.engakuji.or.jp/',
            costs: [{ label: '拝観料', amount: '500' }],
          },
          {
            id: 91,
            name: '鎌倉大仏',
            startTime: '11:00',
            duration: 60,
            category: '観光',
            note: '国宝の高徳院大仏。胴体内部に入れる',
            url: 'https://www.kotoku-in.jp/',
            costs: [{ label: '拝観料', amount: '300' }],
          },
          {
            id: 92,
            name: '小町通り食べ歩き',
            startTime: '13:00',
            duration: 90,
            category: 'グルメ',
            note: '鎌倉の食べ歩きストリート。コロッケが定番',
            url: '',
            costs: [{ label: '食べ歩き', amount: '2000' }],
          },
        ],
      },
      {
        date: '2026-10-04',
        spots: [
          {
            id: 93,
            name: '江ノ島散策',
            startTime: '09:00',
            duration: 120,
            category: '散策',
            note: '江ノ島神社と岩屋洞窟。稚児ヶ淵まで',
            url: 'https://www.enoshima-seacandle.com/',
            costs: [{ label: '江ノ島シーキャンドル', amount: '500' }],
          },
          {
            id: 94,
            name: 'しらす丼ランチ',
            startTime: '12:00',
            duration: 60,
            category: 'グルメ',
            note: '江ノ島の名物しらす。生しらすは季節限定',
            url: '',
            costs: [{ label: '昼食', amount: '1800' }],
          },
          {
            id: 95,
            name: '鎌倉高校前駅',
            startTime: '15:00',
            duration: 30,
            category: '散策',
            note: 'スラムダンクの踏切で有名。夕焼けの江ノ電',
            url: '',
            costs: [],
          },
        ],
      },
    ],
  },
  {
    id: 13,
    title: '日光東照宮と奥日光',
    destination: '栃木',
    startDate: '2026-10-24',
    endDate: '2026-10-25',
    cover: '🍁',
    days: [
      {
        date: '2026-10-24',
        spots: [
          {
            id: 96,
            name: '日光東照宮',
            startTime: '09:30',
            duration: 120,
            category: '観光',
            note: '徳川家康を祀る豪華絢爛な世界遺産の社殿',
            url: 'https://www.toshogu.jp/',
            costs: [{ label: '拝観料', amount: '1300' }],
          },
          {
            id: 97,
            name: '輪王寺',
            startTime: '12:00',
            duration: 60,
            category: '観光',
            note: '三仏堂は日光最大の建物',
            url: 'https://www.rinnoji.or.jp/',
            costs: [{ label: '拝観料', amount: '400' }],
          },
          {
            id: 98,
            name: '日光金谷ホテル',
            startTime: '17:00',
            duration: 120,
            category: '宿泊',
            note: '創業150年の老舗リゾートホテル。国内最古のリゾートホテル',
            url: 'https://www.kanayahotel.co.jp/',
            costs: [{ label: '宿泊費（夕食込み）', amount: '35000' }],
          },
        ],
      },
      {
        date: '2026-10-25',
        spots: [
          {
            id: 99,
            name: '華厳の滝',
            startTime: '08:30',
            duration: 45,
            category: '観光',
            note: '日本三名瀑のひとつ。エレベーターで展望台へ',
            url: 'https://www.kegon.jp/',
            costs: [{ label: 'エレベーター代', amount: '570' }],
          },
          {
            id: 100,
            name: '中禅寺湖',
            startTime: '10:00',
            duration: 90,
            category: '散策',
            note: '紅葉の季節は絶景。遊覧船もおすすめ',
            url: '',
            costs: [{ label: '遊覧船', amount: '1100' }],
          },
          {
            id: 101,
            name: '戦場ヶ原ハイキング',
            startTime: '12:30',
            duration: 120,
            category: '体験',
            note: '湿原の木道ハイキング。紅葉と自然の景色',
            url: '',
            costs: [],
          },
        ],
      },
    ],
  },
  {
    id: 14,
    title: '白川郷・飛騨高山',
    destination: '岐阜',
    startDate: '2026-01-17',
    endDate: '2026-01-18',
    cover: '🏔️',
    days: [
      {
        date: '2026-01-17',
        spots: [
          {
            id: 102,
            name: '飛騨高山古い町並み',
            startTime: '10:00',
            duration: 90,
            category: '散策',
            note: '江戸時代の商家が立ち並ぶ三之町。みたらし団子が名物',
            url: 'https://www.hidatakayama.or.jp/',
            costs: [{ label: 'みたらし団子', amount: '200' }],
          },
          {
            id: 103,
            name: '飛騨の里',
            startTime: '12:30',
            duration: 90,
            category: '観光',
            note: '合掌造り民家が移築・保存されている野外博物館',
            url: 'https://www.hidanosato-tpo.jp/',
            costs: [{ label: '入場料', amount: '700' }],
          },
          {
            id: 104,
            name: '飛騨高山ラーメン',
            startTime: '15:00',
            duration: 60,
            category: 'グルメ',
            note: '薄口醤油の澄んだスープが特徴の地元ラーメン',
            url: '',
            costs: [{ label: '昼食', amount: '900' }],
          },
          {
            id: 105,
            name: '合掌造り民宿',
            startTime: '17:00',
            duration: 120,
            category: '宿泊',
            note: '白川郷の合掌造り家屋に宿泊。囲炉裏を囲んで夕食',
            url: '',
            costs: [{ label: '宿泊（夕食付き）', amount: '18000' }],
          },
        ],
      },
      {
        date: '2026-01-18',
        spots: [
          {
            id: 106,
            name: '白川郷ライトアップ',
            startTime: '18:00',
            duration: 90,
            category: '観光',
            note: '冬季限定の幻想的なライトアップ。要事前申込（抽選）',
            url: 'https://shirakawa-go.gr.jp/',
            costs: [],
          },
          {
            id: 107,
            name: '相倉合掌造り集落',
            startTime: '10:00',
            duration: 90,
            category: '観光',
            note: 'ユネスコ世界遺産。荻町よりも静かで穴場',
            url: '',
            costs: [{ label: '駐車料金', amount: '500' }],
          },
          {
            id: 108,
            name: '飛騨牛にぎり',
            startTime: '13:00',
            duration: 45,
            category: 'グルメ',
            note: '飛騨牛の握り寿司。濃厚な霜降りが絶品',
            url: '',
            costs: [{ label: '飛騨牛にぎり', amount: '3000' }],
          },
        ],
      },
    ],
  },
  {
    id: 15,
    title: '軽井沢避暑旅行',
    destination: '長野',
    startDate: '2026-08-08',
    endDate: '2026-08-10',
    cover: '🌿',
    days: [
      {
        date: '2026-08-08',
        spots: [
          {
            id: 109,
            name: '旧軽井沢銀座通り',
            startTime: '11:00',
            duration: 90,
            category: '散策',
            note: '避暑地の中心街。ジャム・チーズ・スコーンの名店が並ぶ',
            url: '',
            costs: [{ label: '食べ歩き', amount: '2000' }],
          },
          {
            id: 110,
            name: '雲場池',
            startTime: '13:30',
            duration: 45,
            category: '散策',
            note: '「スワンレイク」とも呼ばれる美しい池',
            url: '',
            costs: [],
          },
          {
            id: 111,
            name: '万平ホテル アフタヌーンティー',
            startTime: '15:00',
            duration: 60,
            category: '体験',
            note: 'ジョン・レノンも愛した老舗ホテルでアフタヌーンティー',
            url: 'https://www.manpei-hotel.co.jp/',
            costs: [{ label: 'アフタヌーンティー', amount: '3000' }],
          },
        ],
      },
      {
        date: '2026-08-09',
        spots: [
          {
            id: 112,
            name: '軽井沢高原教会',
            startTime: '09:00',
            duration: 45,
            category: '観光',
            note: '木立の中に建つロマンチックな礼拝堂',
            url: 'https://www.karuizawa-highlandchurch.com/',
            costs: [],
          },
          {
            id: 113,
            name: '浅間山眺望ドライブ',
            startTime: '11:00',
            duration: 90,
            category: '散策',
            note: '活火山の浅間山を望む高原ドライブ',
            url: '',
            costs: [{ label: 'ガソリン', amount: '1500' }],
          },
          {
            id: 114,
            name: '信州牛BBQディナー',
            startTime: '17:30',
            duration: 120,
            category: 'グルメ',
            note: '信州牛と高原野菜のBBQ',
            url: '',
            costs: [{ label: '食材費', amount: '4000' }],
          },
        ],
      },
      {
        date: '2026-08-10',
        spots: [
          {
            id: 115,
            name: '北軽井沢浅間牧場',
            startTime: '09:00',
            duration: 90,
            category: '体験',
            note: '広大な牧場でソフトクリームと馬との触れ合い',
            url: '',
            costs: [{ label: '入場料・ソフトクリーム', amount: '800' }],
          },
          {
            id: 116,
            name: '軽井沢プリンスショッピングプラザ',
            startTime: '12:00',
            duration: 120,
            category: '散策',
            note: '帰りに話題のアウトレットでショッピング',
            url: 'https://www.karuizawa-psp.jp/',
            costs: [{ label: 'ショッピング', amount: '8000' }],
          },
        ],
      },
    ],
  },
  {
    id: 16,
    title: '高知・四万十川の旅',
    destination: '高知',
    startDate: '2026-07-04',
    endDate: '2026-07-06',
    cover: '🏞️',
    days: [
      {
        date: '2026-07-04',
        spots: [
          {
            id: 117,
            name: '高知城',
            startTime: '10:00',
            duration: 90,
            category: '観光',
            note: '天守から本丸御殿まで現存する稀有な城。坂本龍馬像が近い',
            url: 'https://www.kochipark.jp/kochijyo/',
            costs: [{ label: '入場料', amount: '420' }],
          },
          {
            id: 118,
            name: 'ひろめ市場',
            startTime: '12:30',
            duration: 90,
            category: 'グルメ',
            note: 'かつおのたたきを目の前で藁焼き。土佐の食文化を体感',
            url: 'https://www.hirome.co.jp/',
            costs: [{ label: '昼食', amount: '2000' }],
          },
          {
            id: 119,
            name: 'カツオのたたき居酒屋',
            startTime: '18:00',
            duration: 90,
            category: 'グルメ',
            note: '土佐鶴と一緒に本場のかつおのたたきを',
            url: '',
            costs: [{ label: '夕食', amount: '3500' }],
          },
        ],
      },
      {
        date: '2026-07-05',
        spots: [
          {
            id: 120,
            name: '四万十川カヌー体験',
            startTime: '09:00',
            duration: 180,
            category: '体験',
            note: '日本最後の清流でカヌー。川の透明度が素晴らしい',
            url: '',
            costs: [{ label: 'カヌーツアー代', amount: '6000' }],
          },
          {
            id: 121,
            name: '四万十川の沈下橋',
            startTime: '13:30',
            duration: 60,
            category: '散策',
            note: '欄干のない橋は増水時に沈む。地元の生活に溶け込む橋',
            url: '',
            costs: [],
          },
          {
            id: 122,
            name: '天然うなぎ夕食',
            startTime: '18:00',
            duration: 90,
            category: 'グルメ',
            note: '四万十川の天然うなぎは絶品。予約必須',
            url: '',
            costs: [{ label: '夕食（うな重）', amount: '5500' }],
          },
        ],
      },
      {
        date: '2026-07-06',
        spots: [
          {
            id: 123,
            name: '桂浜',
            startTime: '09:00',
            duration: 60,
            category: '観光',
            note: '龍馬像と太平洋の大海原。月の名所として有名',
            url: 'https://katsurahama-t.jp/',
            costs: [],
          },
          {
            id: 124,
            name: '牧野植物園',
            startTime: '11:00',
            duration: 90,
            category: '観光',
            note: '朝ドラ「らんまん」のモデル・牧野富太郎の植物園',
            url: 'https://www.makino.or.jp/',
            costs: [{ label: '入場料', amount: '730' }],
          },
          {
            id: 125,
            name: '高知空港お土産',
            startTime: '14:30',
            duration: 30,
            category: '散策',
            note: '「芋けんぴ」と「土佐日記」を購入',
            url: '',
            costs: [{ label: 'お土産', amount: '2000' }],
          },
        ],
      },
    ],
  },
  {
    id: 17,
    title: '福岡・太宰府',
    destination: '福岡',
    startDate: '2026-04-18',
    endDate: '2026-04-19',
    cover: '🍜',
    days: [
      {
        date: '2026-04-18',
        spots: [
          {
            id: 126,
            name: '中洲屋台ランチ',
            startTime: '12:00',
            duration: 90,
            category: 'グルメ',
            note: '昼から開いている屋台で博多ラーメンを',
            url: '',
            costs: [{ label: '昼食', amount: '900' }],
          },
          {
            id: 127,
            name: '博多旧市街散策',
            startTime: '14:30',
            duration: 60,
            category: '散策',
            note: '承天寺（博多発祥うどん）など裏路地の文化を歩く',
            url: '',
            costs: [],
          },
          {
            id: 128,
            name: 'もつ鍋ディナー',
            startTime: '18:00',
            duration: 90,
            category: 'グルメ',
            note: '博多名物のもつ鍋。コラーゲンたっぷり',
            url: '',
            costs: [{ label: '夕食', amount: '3000' }],
          },
        ],
      },
      {
        date: '2026-04-19',
        spots: [
          {
            id: 129,
            name: '太宰府天満宮',
            startTime: '09:30',
            duration: 90,
            category: '観光',
            note: '学問の神様・菅原道真公を祀る。受験生に大人気',
            url: 'https://www.dazaifutenmangu.or.jp/',
            costs: [{ label: 'お守り', amount: '800' }],
          },
          {
            id: 130,
            name: '梅ヶ枝餅',
            startTime: '11:30',
            duration: 30,
            category: 'グルメ',
            note: '太宰府名物。焼きたてが美味。参道に多数の店',
            url: '',
            costs: [{ label: '梅ヶ枝餅', amount: '500' }],
          },
          {
            id: 131,
            name: '九州国立博物館',
            startTime: '12:30',
            duration: 90,
            category: '観光',
            note: '太宰府天満宮に隣接。アジアの文化交流史',
            url: 'https://www.kyuhaku.jp/',
            costs: [{ label: '入館料', amount: '700' }],
          },
          {
            id: 132,
            name: '中洲屋台（夜）',
            startTime: '19:00',
            duration: 90,
            category: 'グルメ',
            note: '夜の屋台は雰囲気が最高。焼き鳥と明太子',
            url: '',
            costs: [{ label: '夕食', amount: '2500' }],
          },
        ],
      },
    ],
  },
  {
    id: 18,
    title: '熊野古道・那智の滝',
    destination: '和歌山・三重',
    startDate: '2026-10-10',
    endDate: '2026-10-12',
    cover: '🌿',
    days: [
      {
        date: '2026-10-10',
        spots: [
          {
            id: 133,
            name: '熊野本宮大社',
            startTime: '10:00',
            duration: 60,
            category: '観光',
            note: '熊野三山のひとつ。八咫烏が神の使い',
            url: 'https://www.hongutaisha.jp/',
            costs: [{ label: 'お守り', amount: '500' }],
          },
          {
            id: 134,
            name: '大斎原（おおゆのはら）',
            startTime: '11:30',
            duration: 45,
            category: '散策',
            note: '日本最大の鳥居。かつての本宮跡地',
            url: '',
            costs: [],
          },
          {
            id: 135,
            name: '川湯温泉',
            startTime: '14:00',
            duration: 90,
            category: '体験',
            note: '熊野川の河原に湧く天然温泉。仙人風呂は冬季限定',
            url: '',
            costs: [{ label: '入浴料', amount: '600' }],
          },
        ],
      },
      {
        date: '2026-10-11',
        spots: [
          {
            id: 136,
            name: '熊野古道（中辺路）歩き',
            startTime: '08:00',
            duration: 240,
            category: '体験',
            note: '一番人気のルートを歩く。熊野那智大社へ向かう',
            url: '',
            costs: [],
          },
          {
            id: 137,
            name: '熊野那智大社',
            startTime: '13:00',
            duration: 60,
            category: '観光',
            note: '那智の滝を御神体とする熊野三山のひとつ',
            url: 'https://www.nachisan.org/',
            costs: [],
          },
          {
            id: 138,
            name: '那智の滝',
            startTime: '14:30',
            duration: 45,
            category: '観光',
            note: '落差133mの日本一の直瀑。飛瀧神社の御神体',
            url: '',
            costs: [{ label: '飛瀧神社拝観料', amount: '300' }],
          },
        ],
      },
      {
        date: '2026-10-12',
        spots: [
          {
            id: 139,
            name: '熊野速玉大社',
            startTime: '09:00',
            duration: 45,
            category: '観光',
            note: '熊野三山を結ぶ最後の社。境内の梛（なぎ）の木',
            url: 'https://www.kumanohayatama.jp/',
            costs: [],
          },
          {
            id: 140,
            name: '鬼ヶ城',
            startTime: '11:00',
            duration: 90,
            category: '散策',
            note: '世界遺産の海岸地形。奇岩と洞窟の連続',
            url: '',
            costs: [],
          },
          {
            id: 141,
            name: '伊勢神宮外宮',
            startTime: '14:30',
            duration: 60,
            category: '観光',
            note: '帰路で立ち寄り。豊受大神宮。食の神',
            url: 'https://www.isejingu.or.jp/',
            costs: [],
          },
        ],
      },
    ],
  },
  {
    id: 19,
    title: '草津温泉',
    destination: '群馬',
    startDate: '2026-12-05',
    endDate: '2026-12-06',
    cover: '♨️',
    days: [
      {
        date: '2026-12-05',
        spots: [
          {
            id: 142,
            name: '湯畑',
            startTime: '13:00',
            duration: 45,
            category: '散策',
            note: '草津温泉の中心。毎分4,000Lの湯が湧き出る圧巻の光景',
            url: 'https://www.kusatsu-onsen.ne.jp/',
            costs: [],
          },
          {
            id: 143,
            name: '時間湯体験',
            startTime: '14:30',
            duration: 60,
            category: '体験',
            note: '地元の湯もみと入湯式の伝統行事に参加',
            url: '',
            costs: [{ label: '体験料', amount: '600' }],
          },
          {
            id: 144,
            name: '温泉旅館チェックイン',
            startTime: '16:00',
            duration: 120,
            category: '宿泊',
            note: '源泉かけ流しの旅館。夕食は上州牛のしゃぶしゃぶ',
            url: '',
            costs: [{ label: '宿泊費（1泊2食）', amount: '22000' }],
          },
          {
            id: 145,
            name: '西の河原露天風呂',
            startTime: '20:00',
            duration: 60,
            category: '体験',
            note: '夜の大露天風呂は星空が見え幻想的',
            url: 'https://www.sainokawara.com/',
            costs: [{ label: '入浴料', amount: '600' }],
          },
        ],
      },
      {
        date: '2026-12-06',
        spots: [
          {
            id: 146,
            name: '朝風呂',
            startTime: '07:00',
            duration: 45,
            category: '体験',
            note: '旅館の源泉かけ流し朝風呂で一日をスタート',
            url: '',
            costs: [],
          },
          {
            id: 147,
            name: '草津温泉街散策',
            startTime: '09:00',
            duration: 60,
            category: '散策',
            note: '地元産の野菜と草津温泉みやげ。湯の花が名産',
            url: '',
            costs: [{ label: 'お土産', amount: '2500' }],
          },
          {
            id: 148,
            name: '草津白根山（弓池）',
            startTime: '11:00',
            duration: 90,
            category: '散策',
            note: '白根山は活火山のため立入禁止区域あり。弓池周辺の散策',
            url: '',
            costs: [],
          },
        ],
      },
    ],
  },
  {
    id: 20,
    title: '函館・小樽ロマン旅',
    destination: '北海道（函館・小樽）',
    startDate: '2026-11-14',
    endDate: '2026-11-16',
    cover: '🦞',
    days: [
      {
        date: '2026-11-14',
        spots: [
          {
            id: 149,
            name: '函館朝市',
            startTime: '08:00',
            duration: 90,
            category: 'グルメ',
            note: 'イカの踊り食いと海鮮丼。早起きして新鮮なうちに',
            url: 'https://www.hakodate-asaichi.com/',
            costs: [{ label: '朝食', amount: '2500' }],
          },
          {
            id: 150,
            name: '函館元町エリア',
            startTime: '10:30',
            duration: 90,
            category: '散策',
            note: '教会群と洋館が立ち並ぶ異国情緒あふれる丘の街',
            url: '',
            costs: [],
          },
          {
            id: 151,
            name: '旧函館区公会堂',
            startTime: '13:00',
            duration: 45,
            category: '観光',
            note: '明治時代の格調高い洋風建築。函館湾を一望',
            url: 'https://www.zaidan-hakodate.com/koukaidou/',
            costs: [{ label: '入場料', amount: '300' }],
          },
          {
            id: 152,
            name: '函館山夜景',
            startTime: '20:00',
            duration: 60,
            category: '観光',
            note: '世界三大夜景のひとつ。ロープウェイで山頂へ',
            url: 'https://334.co.jp/',
            costs: [{ label: 'ロープウェイ', amount: '1500' }],
          },
        ],
      },
      {
        date: '2026-11-15',
        spots: [
          {
            id: 153,
            name: '小樽運河',
            startTime: '10:00',
            duration: 90,
            category: '散策',
            note: '石造り倉庫とガス灯。北海道の明治・大正ロマン',
            url: 'https://otaru.gr.jp/',
            costs: [],
          },
          {
            id: 154,
            name: '小樽寿司屋通り',
            startTime: '12:30',
            duration: 90,
            category: 'グルメ',
            note: '北海道の新鮮なネタが並ぶ。ウニとイクラが旬',
            url: '',
            costs: [{ label: '昼食（寿司）', amount: '5000' }],
          },
          {
            id: 155,
            name: '北一硝子',
            startTime: '15:00',
            duration: 60,
            category: '散策',
            note: '明治時代の石造り倉庫を利用したガラス専門店',
            url: 'https://www.kitaichiglass.co.jp/',
            costs: [{ label: 'ガラス雑貨', amount: '3000' }],
          },
          {
            id: 156,
            name: '小樽ビール館',
            startTime: '17:00',
            duration: 90,
            category: 'グルメ',
            note: '運河プラザの地ビール館で北海道の海鮮と地ビール',
            url: '',
            costs: [{ label: '夕食', amount: '4000' }],
          },
        ],
      },
      {
        date: '2026-11-16',
        spots: [
          {
            id: 157,
            name: '天狗山ロープウェイ',
            startTime: '09:00',
            duration: 60,
            category: '観光',
            note: '小樽の街と石狩湾を一望。冬はスキー場になる',
            url: '',
            costs: [{ label: 'ロープウェイ', amount: '800' }],
          },
          {
            id: 158,
            name: '新千歳空港グルメ',
            startTime: '12:00',
            duration: 90,
            category: 'グルメ',
            note: '新千歳空港のフードコートでラーメンやスープカレー',
            url: '',
            costs: [{ label: '空港ランチ', amount: '1200' }],
          },
          {
            id: 159,
            name: 'ロイズチョコレート',
            startTime: '14:00',
            duration: 30,
            category: 'グルメ',
            note: '新千歳空港限定のロイズチョコレートをお土産に',
            url: 'https://www.royce.com/',
            costs: [{ label: 'チョコレート', amount: '3000' }],
          },
        ],
      },
    ],
  },
];

function isClient(): boolean {
  return typeof window !== 'undefined';
}

function loadFromStorage(): Trip[] {
  if (!isClient()) return sampleTrips;
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as Trip[];
  } catch {
    // corrupted data — fall through to seed
  }
  // First visit: seed with sample trips
  saveToStorage(sampleTrips);
  return sampleTrips;
}

function saveToStorage(data: Trip[]): void {
  if (!isClient()) return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch {
    // storage quota exceeded — ignore
  }
}

function maxId(data: Trip[]): number {
  return data
    .flatMap((trip) => trip.days.flatMap((day) => day.spots.map((spot) => spot.id)))
    .reduce((max, id) => Math.max(max, id), 0);
}

// Lazily initialized on first access
let _trips: Trip[] | null = null;
let _nextTripId: number | null = null;
let _nextSpotId: number | null = null;

function ensureLoaded(): void {
  if (_trips !== null) return;
  _trips = loadFromStorage();
  _nextTripId = _trips.reduce((max, t) => Math.max(max, t.id), 0) + 1;
  _nextSpotId = maxId(_trips) + 1;
}

export function getTrips(): Trip[] {
  ensureLoaded();
  return _trips!;
}

export function getTrip(id: number): Trip | undefined {
  ensureLoaded();
  return _trips!.find((t) => t.id === id);
}

export function addTrip(data: Omit<Trip, 'id' | 'days'>): Trip {
  ensureLoaded();
  const newTrip: Trip = { ...data, id: _nextTripId!++, days: generateDays(data.startDate, data.endDate) };
  _trips = [..._trips!, newTrip];
  saveToStorage(_trips);
  return newTrip;
}

export function updateTrip(trip: Trip): void {
  ensureLoaded();
  _trips = _trips!.map((t) => (t.id === trip.id ? trip : t));
  saveToStorage(_trips);
}

export function deleteTrip(id: number): void {
  ensureLoaded();
  _trips = _trips!.filter((t) => t.id !== id);
  saveToStorage(_trips);
}

export async function hashPassword(password: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(password);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  return Array.from(new Uint8Array(hashBuffer)).map((b) => b.toString(16).padStart(2, '0')).join('');
}

export function nextSpotId_get(): number {
  ensureLoaded();
  return _nextSpotId!++;
}

function generateDays(startDate: string, endDate: string): Day[] {
  const days: Day[] = [];
  const current = new Date(startDate + 'T00:00:00');
  const end = new Date(endDate + 'T00:00:00');
  while (current <= end) {
    days.push({ date: current.toISOString().slice(0, 10), spots: [] });
    current.setDate(current.getDate() + 1);
  }
  return days;
}
